category: Navigation
created: '2026-06-01'
display_name_ru: 'header: minimal'
has_bg_image: false
id: header-003
layout_pattern: minimal
signature: header|minimal|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: header
