#!/usr/bin/env python3
"""Generate a starter moodboard.md narrative from approved references in refs_dir/index.yaml.

CLI: python3 scaffold.py <refs-dir> [--project <name>] [--output <path>]

The generated file has sections ready for the moodboard-composer agent to fill in.
Each section includes reference-derived bullets as starting points.
"""
import argparse
import sys
from pathlib import Path
from typing import Optional
import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))

from tools.logger import success, error


_SECTIONS = [
    "## Direction",
    "## Adopted patterns",
    "## Rejected patterns",
    "## Color feel",
    "## Typography character",
    "## Motion vibe",
]


def scaffold_moodboard(refs_dir: str, output_md: Optional[str] = None, project_name: str = "Project") -> Path:
    """Generate a starter moodboard.md from approved references in refs_dir/index.yaml.

    Args:
        refs_dir: path to 03_РЕФЕРЕНСЫ/ folder containing index.yaml
        output_md: where to write the output (defaults to refs_dir/moodboard.md)
        project_name: project name used in the file heading

    Returns:
        Path to the written file.
    """
    refs = Path(refs_dir)
    idx = refs / "index.yaml"

    approved = []
    rejected = []
    if idx.exists():
        data = yaml.safe_load(idx.read_text(encoding="utf-8")) or {"references": []}
        all_refs = data.get("references", [])
        approved = [r for r in all_refs if r.get("status") == "approved"]
        rejected = [r for r in all_refs if r.get("status") == "rejected"]

    lines = [
        f"# Moodboard — {project_name}",
        "",
        "> Auto-generated by scaffold.py. Fill in each section with your creative direction.",
        "",
    ]

    # Direction section
    lines.append("## Direction")
    lines.append("")
    if approved:
        lines.append("Based on the approved references, the visual direction is:")
        lines.append("")
        for r in approved:
            val = r.get("value", "")
            lines.append(f"- {val}")
    else:
        lines.append("- *No approved references yet — add some via index.py add*")
    lines.append("")

    # Adopted patterns
    lines.append("## Adopted patterns")
    lines.append("")
    if approved:
        for r in approved:
            val = r.get("value", "")
            # Use URL stem as pattern hint
            stem = val.rstrip("/").split("/")[-1] or val.split("//")[-1].split("/")[0]
            lines.append(f"- From `{stem}`: *describe what visual pattern to adopt*")
    else:
        lines.append("- *Fill in after reviewing approved references*")
    lines.append("")

    # Rejected patterns
    lines.append("## Rejected patterns")
    lines.append("")
    if rejected:
        for r in rejected:
            val = r.get("value", "")
            lines.append(f"- {val} — *describe what to avoid*")
    else:
        lines.append("- *Fill in patterns explicitly rejected from candidate references*")
    lines.append("")

    # Color feel
    lines.append("## Color feel")
    lines.append("")
    lines.append("- Primary palette: *e.g. deep navy + warm cream + electric accent*")
    lines.append("- Mood: *e.g. premium, calm, energetic*")
    lines.append("- Contrast level: *e.g. high contrast for impact*")
    lines.append("")

    # Typography character
    lines.append("## Typography character")
    lines.append("")
    lines.append("- Display font: *e.g. Cabinet Grotesk — bold, editorial*")
    lines.append("- Body font: *e.g. Inter — clean, readable*")
    lines.append("- Weight range: *e.g. 400–800*")
    lines.append("")

    # Motion vibe
    lines.append("## Motion vibe")
    lines.append("")
    lines.append("- Transitions: *e.g. smooth easing, 300ms*")
    lines.append("- Scroll behavior: *e.g. subtle parallax on hero*")
    lines.append("- Micro-interactions: *e.g. button scale on hover*")
    lines.append("")

    content = "\n".join(lines)
    out_path = Path(output_md) if output_md else refs / "moodboard.md"
    out_path.write_text(content, encoding="utf-8")
    return out_path


def main(argv: list) -> int:
    p = argparse.ArgumentParser(description="Generate starter moodboard.md from approved references")
    p.add_argument("refs_dir", help="Path to 03_РЕФЕРЕНСЫ/ folder")
    p.add_argument("--project", default="Project", help="Project name")
    p.add_argument("--output", default=None, help="Output file path (default: refs_dir/moodboard.md)")
    args = p.parse_args(argv[1:])
    try:
        out = scaffold_moodboard(args.refs_dir, args.output, args.project)
        success(f"Wrote {out}")
        return 0
    except Exception as exc:
        error(f"scaffold failed: {exc}")
        return 1


if __name__ == "__main__":
    sys.exit(main(sys.argv))
