category: Content
created: '2026-06-01'
display_name_ru: 'features: grid'
has_bg_image: false
id: features-003
layout_pattern: grid
signature: features|grid|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: features
