#!/usr/bin/env python3
"""Verify every block.php under wp-theme/blocks/lazyblock-* starts with the
frontend-builder marker comment.

Exit 0: all blocks have marker (or no blocks present).
Exit 1: at least one block.php is missing the marker.

Usage: check-block-php-markers.py <project-dir>
"""
import sys
from pathlib import Path

MARKER_LINES = (
    "<?php",
    "// AUTO-GENERATED by frontend-builder.",
    "// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.",
)


def main(argv: list) -> int:
    if len(argv) < 2:
        print("usage: check-block-php-markers.py <project-dir>", file=sys.stderr)
        return 2
    project = Path(argv[1])
    blocks_dir = project / "08_КОД" / "wp-theme" / "blocks"
    if not blocks_dir.exists():
        return 0
    missing: list[str] = []
    for block_php in sorted(blocks_dir.glob("lazyblock-*/block.php")):
        text = block_php.read_text(encoding="utf-8")
        head = "\n".join(text.splitlines()[:3])
        if not all(line in head for line in MARKER_LINES):
            missing.append(block_php.parent.name)
    if missing:
        print(f"missing frontend-builder marker in: {', '.join(missing)}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
