#!/usr/bin/env python3
"""Inject (or update) AUTO-GENERATED block registration section in functions.php.

CLI: python generate-block-registration.py --project <path>
"""
import argparse
import re
import shutil
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
sys.path.insert(0, str(REPO_ROOT / "scripts" / "lib"))

from content_parser import ContentParser, ContentParseError  # noqa: E402

MARKER_START = "// AUTO-GENERATED START: lp-block-registration — DO NOT EDIT MANUALLY"
MARKER_END = "// AUTO-GENERATED END"
SECTION_RE = re.compile(
    r"\n?// AUTO-GENERATED START: lp-block-registration.*?// AUTO-GENERATED END\n?",
    re.DOTALL,
)


def _render_section(slugs: list[str]) -> str:
    slug_php = ", ".join(f"'{s}'" for s in slugs)
    return f"""
{MARKER_START}
//                      Regenerated by generate-block-registration.py
if ( ! function_exists( 'lp_register_block_category' ) ) {{
    function lp_register_block_category( $categories ) {{
        return array_merge(
            $categories,
            [ [ 'slug' => 'lp-blocks', 'title' => 'Landing-page blocks', 'icon' => null ] ]
        );
    }}
    add_filter( 'block_categories_all', 'lp_register_block_category' );
}}

if ( ! function_exists( 'lp_register_acf_blocks' ) ) {{
    function lp_register_acf_blocks() {{
        $blocks = [ {slug_php} ];
        foreach ( $blocks as $slug ) {{
            $path = get_template_directory() . '/../../gutenberg-blocks/' . $slug;
            if ( file_exists( $path . '/block.json' ) ) {{
                register_block_type( $path );
            }}
        }}
    }}
    add_action( 'init', 'lp_register_acf_blocks' );
}}
{MARKER_END}
"""


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    args = ap.parse_args()

    src = Path(args.project) / "07_КОНТЕНТ" / "final-copy.md"
    try:
        blocks = ContentParser.parse(str(src))
        ContentParser.validate(blocks)
    except ContentParseError as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)

    fn_php = Path(args.project) / "08_КОД" / "wp-theme" / "functions.php"
    if not fn_php.exists():
        print(f"ERROR: {fn_php} not found", file=sys.stderr)
        sys.exit(1)

    shutil.copy2(fn_php, fn_php.with_suffix(".php.bak"))
    src_text = fn_php.read_text(encoding="utf-8")

    section = _render_section([b.slug for b in blocks])

    if SECTION_RE.search(src_text):
        new_text = SECTION_RE.sub(section, src_text)
    else:
        # Append to end of file (after last `?>` if present, or just append)
        if src_text.rstrip().endswith("?>"):
            new_text = src_text.rstrip()[:-2].rstrip() + "\n" + section + "\n?>\n"
        else:
            new_text = src_text.rstrip() + "\n" + section

    fn_php.write_text(new_text, encoding="utf-8", newline="\n")
    print(f"wrote {fn_php} (registered {len(blocks)} block(s))")


if __name__ == "__main__":
    main()
