#!/usr/bin/env python3
"""Generate WordPress theme scaffold from tokens.json + design-stack.yaml.

CLI: python3 generate-theme.py <project-dir>
Stdout: path to created wp-theme/ directory
"""
import json
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from tools.logger import error, info, success


def _find_project_root(start: Path) -> Path:
    for parent in [start, *start.parents]:
        if (parent / "05_ДИЗАЙН-СИСТЕМА" / "tokens.json").exists():
            return parent
    raise FileNotFoundError("tokens.json not found — run /landing-design first")


def _load_tokens(project: Path) -> dict:
    return json.loads((project / "05_ДИЗАЙН-СИСТЕМА" / "tokens.json").read_text(encoding="utf-8"))


def _load_stack(project: Path) -> dict:
    p = project / "06_СТЕК" / "design-stack.yaml"
    return yaml.safe_load(p.read_text(encoding="utf-8")) if p.exists() else {}


def _css_variables(tokens: dict) -> str:
    lines = [":root {"]
    for name, props in tokens.get("colors", {}).items():
        hex_val = props["hex"] if isinstance(props, dict) else str(props)
        lines.append(f"  --color-{name}: {hex_val};")
    for role, props in tokens.get("typography", {}).items():
        if not isinstance(props, dict):
            continue
        lines.append(f"  --font-{role}-family: '{props.get('family', 'sans-serif')}', sans-serif;")
        lines.append(f"  --font-{role}-size: {props.get('size', '1rem')};")
        lines.append(f"  --font-{role}-weight: {props.get('weight', '400')};")
        lines.append(f"  --font-{role}-line-height: {props.get('line_height', '1.5')};")
    for key, val in tokens.get("spacing", {}).items():
        lines.append(f"  --space-{key}: {val};")
    for key, val in tokens.get("radius", {}).items():
        lines.append(f"  --radius-{key}: {val};")
    for key, val in tokens.get("shadow", {}).items():
        lines.append(f"  --shadow-{key}: {val};")
    lines.append("}")
    return "\n".join(lines)


def _write_style_css(theme_dir: Path, project_name: str, tokens: dict) -> None:
    css_vars = _css_variables(tokens)
    (theme_dir / "style.css").write_text(
        f"""/*
Theme Name: LP {project_name}
Description: Landing page theme generated by landing-system wp-builder
Version: 1.0
Text Domain: lp-{project_name.lower().replace(' ', '-')}
*/

{css_vars}
""",
        encoding="utf-8",
    )


def _write_functions_php(theme_dir: Path, stack: dict) -> None:
    fonts = stack.get("fonts", {})
    cdn = fonts.get("cdn", "bunny")
    families = fonts.get("families", [])

    base_url = "https://fonts.bunny.net/css" if cdn == "bunny" else "https://fonts.googleapis.com/css2"
    font_query = "|".join(
        f"{f.get('name', f.get('family', 'inter')).lower().replace(' ', '-')}:{','.join(str(w) for w in f.get('weights', [400]))}"
        for f in families
    )
    font_url = f"{base_url}?family={font_query}" if font_query else f"{base_url}?family=inter:400"

    js_libs = stack.get("js_libraries", [])
    js_lines = []
    if "gsap" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('gsap', "
            "'https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js', [], null, true);"
        )
    if "scrolltrigger" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('gsap-st', "
            "'https://cdn.jsdelivr.net/npm/gsap@3/dist/ScrollTrigger.min.js', ['gsap'], null, true);"
        )
    if "lenis" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('lenis', "
            "'https://cdn.jsdelivr.net/npm/@studio-freight/lenis', [], null, true);"
        )
    if "split-type" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('split-type', "
            "'https://cdn.jsdelivr.net/npm/split-type', [], null, true);"
        )
    js_block = ("\n" + "\n".join(js_lines)) if js_lines else ""

    (theme_dir / "functions.php").write_text(
        f"""<?php
/**
 * Theme functions — generated by landing-system wp-builder
 * DO NOT EDIT manually; re-run /landing-build to regenerate scaffold.
 */

function lp_enqueue_assets() {{
    wp_enqueue_style('lp-fonts', '{font_url}', [], null);
    wp_enqueue_style('lp-style', get_template_directory_uri() . '/style.css', [], '1.0');
    wp_enqueue_style('lp-main', get_template_directory_uri() . '/assets/css/main.css', ['lp-style'], '1.0');
    wp_enqueue_script('lp-main', get_template_directory_uri() . '/assets/js/main.js', [], '1.0', true);{js_block}
}}
add_action('wp_enqueue_scripts', 'lp_enqueue_assets');

function lp_setup() {{
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('editor-styles');
    add_theme_support('wp-block-styles');
    add_theme_support('align-wide');
}}
add_action('after_setup_theme', 'lp_setup');

// Placeholders for generated code (filled by agents):
// [YM_COUNTER] — Yandex Metrika (analytics-engineer)
// [SEO_META]   — meta tags (seo-optimizer)
// [FLUENT_WEBHOOK] — form webhook (integrations-engineer)
""",
        encoding="utf-8",
    )


def main(argv: list) -> int:
    cwd = Path(argv[1]) if len(argv) > 1 else Path.cwd()
    try:
        project = _find_project_root(cwd)
    except FileNotFoundError as e:
        error(str(e))
        return 1

    tokens = _load_tokens(project)
    stack = _load_stack(project)
    project_name = project.name.replace("-", " ").title()

    theme_dir = project / "08_КОД" / "wp-theme"
    theme_dir.mkdir(parents=True, exist_ok=True)
    for sub in ["assets/css", "assets/js", "assets/fonts", "assets/icons", "assets/images", "blocks"]:
        (theme_dir / sub).mkdir(parents=True, exist_ok=True)

    _write_style_css(theme_dir, project_name, tokens)
    _write_functions_php(theme_dir, stack)

    # Minimal WP template: emits enqueued head/footer + post content. Front page
    # is a Gutenberg page set via page_on_front; the_content() renders its blocks.
    (theme_dir / "index.php").write_text(
        "<?php if (!defined('ABSPATH')) { exit; } ?>\n"
        "<!DOCTYPE html>\n"
        "<html <?php language_attributes(); ?>>\n"
        "<head>\n"
        "    <meta charset=\"<?php bloginfo('charset'); ?>\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "    <?php wp_head(); ?>\n"
        "</head>\n"
        "<body <?php body_class(); ?>>\n"
        "<?php wp_body_open(); ?>\n"
        "<main id=\"main\" class=\"lp-main\">\n"
        "<?php\n"
        "if (have_posts()) {\n"
        "    while (have_posts()) {\n"
        "        the_post();\n"
        "        the_content();\n"
        "    }\n"
        "}\n"
        "?>\n"
        "</main>\n"
        "<?php wp_footer(); ?>\n"
        "</body>\n"
        "</html>\n",
        encoding="utf-8",
    )

    (theme_dir / "assets" / "css" / "main.css").write_text(
        "/* Block styles — generated by wp-builder agent */\n", encoding="utf-8"
    )
    (theme_dir / "assets" / "js" / "main.js").write_text(
        "// Landing scripts — generated by wp-builder agent\n", encoding="utf-8"
    )

    success(f"Theme scaffold: {theme_dir}")
    print(str(theme_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
