#!/usr/bin/env python3
"""Generate WordPress theme scaffold from DESIGN.md + design-stack.yaml.

CLI: python3 generate-theme.py <project-dir>
Stdout: path to created wp-theme/ directory

DESIGN.md (05_ДИЗАЙН-СИСТЕМА/DESIGN.md) is the canonical source of CSS:
  - §2 "Design tokens" — ``:root { ... }`` declarations → ``style.css``
  - §3–§9 "Grid", "Sections", "Per-block layouts", "Forms", "Motion",
    "Accessibility", "Component states" → ``assets/css/main.css``

Sections >=10 (asset checklist / open questions / sources) are skipped.
If DESIGN.md is missing or has no fenced ``css`` blocks, we write tiny
placeholder files and warn on stderr — the deploy stays functional.

The legacy ``_css_variables`` / token-derivation logic was removed in the
stage-08 refactor; tokens.json is no longer consumed by the theme generator.
"""
import sys
from pathlib import Path

import yaml

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
sys.path.insert(0, str(Path(__file__).resolve().parent / "lib"))
from tools.logger import error, info, success  # noqa: E402

from design_extractor import DesignExtractError, extract  # noqa: E402


def _find_project_root(start: Path) -> Path:
    for parent in [start, *start.parents]:
        if (parent / "05_ДИЗАЙН-СИСТЕМА" / "DESIGN.md").exists():
            return parent
        # Legacy fallback: accept a project that has tokens.json even without
        # DESIGN.md — we'll then fall back to placeholder CSS and warn.
        if (parent / "05_ДИЗАЙН-СИСТЕМА" / "tokens.json").exists():
            return parent
    raise FileNotFoundError(
        "Neither DESIGN.md nor tokens.json found in 05_ДИЗАЙН-СИСТЕМА — run /landing-design first"
    )


def _load_stack(project: Path) -> dict:
    p = project / "06_СТЕК" / "design-stack.yaml"
    return yaml.safe_load(p.read_text(encoding="utf-8")) if p.exists() else {}


def _write_style_css(theme_dir: Path, project_name: str, style_css: str) -> None:
    header = (
        f"/*\n"
        f"Theme Name: LP {project_name}\n"
        f"Description: Landing page theme generated by landing-system wp-builder\n"
        f"Version: 1.0\n"
        f"Text Domain: lp-{project_name.lower().replace(' ', '-')}\n"
        f"*/\n\n"
    )
    body = style_css.strip() if style_css.strip() else ":root {}\n"
    (theme_dir / "style.css").write_text(header + body + "\n", encoding="utf-8")


def _write_main_css(theme_dir: Path, main_css: str) -> None:
    body = main_css.strip() if main_css.strip() else "/* main.css — DESIGN.md had no §3–§9 styles */\n"
    (theme_dir / "assets" / "css" / "main.css").write_text(body + "\n", encoding="utf-8")


def _write_functions_php(theme_dir: Path, stack: dict) -> None:
    fonts = stack.get("fonts", {})
    cdn = fonts.get("cdn", "bunny")
    families = fonts.get("families", [])

    base_url = "https://fonts.bunny.net/css" if cdn == "bunny" else "https://fonts.googleapis.com/css2"
    font_query = "|".join(
        f"{f.get('name', f.get('family', 'inter')).lower().replace(' ', '-')}:{','.join(str(w) for w in f.get('weights', [400]))}"
        for f in families
    )
    font_url = f"{base_url}?family={font_query}" if font_query else f"{base_url}?family=inter:400"

    js_libs = stack.get("js_libraries", [])
    js_lines = []
    if "gsap" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('gsap', "
            "'https://cdn.jsdelivr.net/npm/gsap@3/dist/gsap.min.js', [], null, true);"
        )
    if "scrolltrigger" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('gsap-st', "
            "'https://cdn.jsdelivr.net/npm/gsap@3/dist/ScrollTrigger.min.js', ['gsap'], null, true);"
        )
    if "lenis" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('lenis', "
            "'https://cdn.jsdelivr.net/npm/@studio-freight/lenis', [], null, true);"
        )
    if "split-type" in js_libs:
        js_lines.append(
            "    wp_enqueue_script('split-type', "
            "'https://cdn.jsdelivr.net/npm/split-type', [], null, true);"
        )
    js_block = ("\n" + "\n".join(js_lines)) if js_lines else ""

    (theme_dir / "functions.php").write_text(
        f"""<?php
/**
 * Theme functions — generated by landing-system wp-builder
 * DO NOT EDIT manually; re-run /landing-build to regenerate scaffold.
 */

function lp_enqueue_assets() {{
    wp_enqueue_style('lp-fonts', '{font_url}', [], null);
    wp_enqueue_style('lp-style', get_template_directory_uri() . '/style.css', [], '1.0');
    wp_enqueue_style('lp-main', get_template_directory_uri() . '/assets/css/main.css', ['lp-style'], '1.0');
    wp_enqueue_script('lp-main', get_template_directory_uri() . '/assets/js/main.js', [], '1.0', true);{js_block}
}}
add_action('wp_enqueue_scripts', 'lp_enqueue_assets');

function lp_setup() {{
    add_theme_support('title-tag');
    add_theme_support('post-thumbnails');
    add_theme_support('editor-styles');
    add_theme_support('wp-block-styles');
    add_theme_support('align-wide');
}}
add_action('after_setup_theme', 'lp_setup');

// Placeholders for generated code (filled by agents):
// [YM_COUNTER] — Yandex Metrika (analytics-engineer)
// [SEO_META]   — meta tags (seo-optimizer)
// [FLUENT_WEBHOOK] — form webhook (integrations-engineer)
""",
        encoding="utf-8",
    )


def main(argv: list) -> int:
    cwd = Path(argv[1]) if len(argv) > 1 else Path.cwd()
    try:
        project = _find_project_root(cwd)
    except FileNotFoundError as e:
        error(str(e))
        return 1

    stack = _load_stack(project)
    project_name = project.name.replace("-", " ").title()

    theme_dir = project / "08_КОД" / "wp-theme"
    theme_dir.mkdir(parents=True, exist_ok=True)
    for sub in ["assets/css", "assets/js", "assets/fonts", "assets/icons", "assets/images", "blocks"]:
        (theme_dir / sub).mkdir(parents=True, exist_ok=True)

    md_path = project / "05_ДИЗАЙН-СИСТЕМА" / "DESIGN.md"
    try:
        style_css, main_css = extract(md_path)
    except DesignExtractError as e:
        print(f"warn: {e} — writing placeholder CSS", file=sys.stderr)
        style_css, main_css = "", ""
    if not style_css and not main_css:
        info("DESIGN.md had no CSS — writing placeholder style.css + main.css")

    _write_style_css(theme_dir, project_name, style_css)
    _write_main_css(theme_dir, main_css)
    _write_functions_php(theme_dir, stack)

    # Minimal WP template: emits enqueued head/footer + post content. Front page
    # is a Gutenberg page set via page_on_front; the_content() renders its blocks.
    (theme_dir / "index.php").write_text(
        "<?php if (!defined('ABSPATH')) { exit; } ?>\n"
        "<!DOCTYPE html>\n"
        "<html <?php language_attributes(); ?>>\n"
        "<head>\n"
        "    <meta charset=\"<?php bloginfo('charset'); ?>\">\n"
        "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n"
        "    <?php wp_head(); ?>\n"
        "</head>\n"
        "<body <?php body_class(); ?>>\n"
        "<?php wp_body_open(); ?>\n"
        "<main id=\"main\" class=\"lp-main\">\n"
        "<?php\n"
        "if (have_posts()) {\n"
        "    while (have_posts()) {\n"
        "        the_post();\n"
        "        the_content();\n"
        "    }\n"
        "}\n"
        "?>\n"
        "</main>\n"
        "<?php wp_footer(); ?>\n"
        "</body>\n"
        "</html>\n",
        encoding="utf-8",
    )

    (theme_dir / "assets" / "js" / "main.js").write_text(
        "// Landing scripts — generated by wp-builder agent\n", encoding="utf-8"
    )

    success(f"Theme scaffold: {theme_dir}")
    print(str(theme_dir))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
