category: footer
created: '2026-06-01'
display_name_ru: footer-002 (split)
has_bg_image: false
id: footer-002
layout_pattern: split
signature: footer|split|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: footer
variant: null
