category: Conversion
created: '2026-06-01'
display_name_ru: 'cta: default'
has_bg_image: false
id: cta-004
layout_pattern: default
signature: cta|default|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: cta
