category: footer
created: '2026-06-01'
display_name_ru: contacts-002 (grid)
has_bg_image: false
id: contacts-002
layout_pattern: grid
signature: contacts|grid|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: contacts
variant: null
