#!/usr/bin/env bats
# Tests that gate-check.sh recognizes the 08b_style stage and runs its hard checks.

setup() {
  REPO_ROOT="$(cd "$BATS_TEST_DIRNAME/../.." && pwd)"
  PROJECT="$(mktemp -d)"
  mkdir -p "$PROJECT/05_ДИЗАЙН-СИСТЕМА" "$PROJECT/08_КОД/wp-theme/blocks/lazyblock-hero" "$PROJECT/08_КОД/wp-theme/blocks/lazyblock-faq" "$PROJECT/08_КОД/wp-theme/assets/css"
  cat > "$PROJECT/.landing-state.yaml" <<EOF
00_brief: approved
01a_niche_analysis: approved
03_moodboard: approved
04_brand: approved
05_design: approved
06_stack: approved
07_content: approved
08_build: approved
08b_style: pending
EOF
  cat > "$PROJECT/05_ДИЗАЙН-СИСТЕМА/DESIGN.md" <<EOF
# D
## 2. Design tokens
\`\`\`css
:root { --x: 1; }
\`\`\`
## 5. Per-block layouts
### Block 1 — Hero
\`\`\`css
.hero { display: grid; }
\`\`\`
### Block 2 — FAQ
\`\`\`css
.faq__item { display: block; }
\`\`\`
EOF
  # NOTE: marker text must stay in sync with check-block-php-markers.py (Task 2)
  cat > "$PROJECT/08_КОД/wp-theme/blocks/lazyblock-hero/block.php" <<'EOF'
<?php
// AUTO-GENERATED by frontend-builder.
// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.
?>
<section class="hero"></section>
EOF
  cat > "$PROJECT/08_КОД/wp-theme/blocks/lazyblock-faq/block.php" <<'EOF'
<?php
// AUTO-GENERATED by frontend-builder.
// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.
?>
<section class="faq"></section>
EOF
  echo "/* main */" > "$PROJECT/08_КОД/wp-theme/assets/css/main.css"
}

teardown() {
  rm -rf "$PROJECT"
}

@test "08b_style stage is defined and passes hard checks when artifacts present" {
  run bash "$REPO_ROOT/scripts/gate-check.sh" --stage 08b_style --project "$PROJECT" --auto
  [ "$status" -eq 0 ]
}

@test "08b_style fails when block.php missing marker" {
  cat > "$PROJECT/08_КОД/wp-theme/blocks/lazyblock-hero/block.php" <<'EOF'
<?php // no marker
EOF
  run bash "$REPO_ROOT/scripts/gate-check.sh" --stage 08b_style --project "$PROJECT" --auto
  [ "$status" -ne 0 ]
}
