category: Conversion
created: '2026-06-01'
display_name_ru: 'cta: split'
has_bg_image: false
id: cta-006
layout_pattern: split
signature: cta|split|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: cta
