category: Footer
created: '2026-06-01'
display_name_ru: 'footer: minimal'
has_bg_image: false
id: footer-003
layout_pattern: minimal
signature: footer|minimal|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: footer
