category: footer
created: '2026-06-01'
display_name_ru: contacts-003 (split)
has_bg_image: false
id: contacts-003
layout_pattern: split
signature: contacts|split|[content]|bg:false
slots:
- name: brand-aria-label
  type: text
- name: brand-link
  type: text
- name: brand-logo-alt
  type: text
- name: brand-logo
  type: text
- name: eyebrow
  type: text
- name: heading
  type: text
- name: subhead
  type: text
- name: contacts-list-label
  type: text
- name: phone-link
  type: text
- name: phone
  type: text
- name: email-link
  type: text
- name: email
  type: text
- name: address
  type: text
- name: social-list-label
  type: text
- name: social-label-1
  type: text
- name: social-link-1
  type: text
- name: social-icon-1
  type: text
- name: social-label-2
  type: text
- name: social-link-2
  type: text
- name: social-icon-2
  type: text
- name: social-label-3
  type: text
- name: social-link-3
  type: text
- name: social-icon-3
  type: text
- name: form-action
  type: text
- name: form-label
  type: text
- name: form-heading
  type: text
- name: form-subhead
  type: text
- name: name-label
  type: text
- name: name-field-name
  type: text
- name: name-placeholder
  type: text
- name: phone-label
  type: text
- name: phone-field-name
  type: text
- name: phone-placeholder
  type: text
- name: message-label
  type: text
- name: message-field-name
  type: text
- name: message-placeholder
  type: text
- name: consent-field-name
  type: text
- name: consent-text
  type: text
- name: submit-label
  type: text
source: cleaned
type: contacts
variant: null
