category: Footer
created: '2026-06-01'
display_name_ru: 'contacts: split'
has_bg_image: false
id: contacts-003
layout_pattern: split
signature: contacts|split|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: contacts
