<?php
function nu_field($k,$d=""){return $d;}
function nu_field_array($k,$d=array()){return $d;}

// AUTO-GENERATED START: lp-block-registration — DO NOT EDIT MANUALLY
//                      Regenerated by generate-block-registration.py
if ( ! function_exists( 'lp_register_block_category' ) ) {
    function lp_register_block_category( $categories ) {
        return array_merge(
            $categories,
            [ [ 'slug' => 'lp-blocks', 'title' => 'Landing-page blocks', 'icon' => null ] ]
        );
    }
    add_filter( 'block_categories_all', 'lp_register_block_category' );
}

if ( ! function_exists( 'lp_register_acf_blocks' ) ) {
    function lp_register_acf_blocks() {
        $blocks = [ 'hero', 'pricing' ];
        foreach ( $blocks as $slug ) {
            $path = get_template_directory() . '/../../gutenberg-blocks/' . $slug;
            if ( file_exists( $path . '/block.json' ) ) {
                register_block_type( $path );
            }
        }
    }
    add_action( 'init', 'lp_register_acf_blocks' );
}
// AUTO-GENERATED END
