<?php
/**
 * Generated by scripts/generate-axes-filter.py. Do not edit.
 * Registers the lp_preview_panel_axes filter for this theme.
 */

add_filter( 'lp_preview_panel_axes', function ( $axes ) {
    $axes['palette'] = [
        'label'             => 'Палитра',
        'default'           => 'paper-minimal',
        'body_class_prefix' => 'theme-',
        'options' => [
            'paper-minimal' => 'Paper Minimal',
        ],
    ];
    $axes['hero'] = [
        'label'             => 'Hero',
        'default'           => 'static',
        'body_class_prefix' => 'hero--',
        'options' => [
            'static'   => 'Static',
            'parallax' => 'Parallax',
        ],
    ];
    return $axes;
} );
