category: Conversion
created: '2026-06-01'
display_name_ru: 'cta: grid'
has_bg_image: false
id: cta-005
layout_pattern: grid
signature: cta|grid|[content]|bg:false
slots:
- name: content
  type: text
source: cleaned
type: cta
