"""Tests check-block-php-markers.py.

The check passes (exit 0) iff every file matching
<project>/08_КОД/wp-theme/blocks/lazyblock-*/block.php starts with the
frontend-builder marker comment.
"""
import subprocess
import sys
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "scripts" / "check-block-php-markers.py"

MARKER = (
    "<?php\n"
    "// AUTO-GENERATED by frontend-builder.\n"
    "// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.\n"
)


def _make_project(tmp_path: Path, blocks: dict[str, str]) -> Path:
    project = tmp_path / "proj"
    for slug, content in blocks.items():
        d = project / "08_КОД" / "wp-theme" / "blocks" / f"lazyblock-{slug}"
        d.mkdir(parents=True, exist_ok=True)
        (d / "block.php").write_text(content, encoding="utf-8")
    return project


def test_passes_when_all_blocks_have_marker(tmp_path):
    project = _make_project(tmp_path, {"hero": MARKER + "<section></section>"})
    r = subprocess.run([sys.executable, str(SCRIPT), str(project)], capture_output=True, text=True)
    assert r.returncode == 0, r.stderr


def test_fails_when_marker_lines_out_of_order(tmp_path):
    swapped = (
        "<?php\n"
        "// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.\n"
        "// AUTO-GENERATED by frontend-builder.\n"
    )
    project = _make_project(tmp_path, {"hero": swapped + "<section></section>"})
    r = subprocess.run([sys.executable, str(SCRIPT), str(project)], capture_output=True, text=True)
    assert r.returncode != 0
    assert "hero" in r.stderr


def test_fails_when_marker_text_present_but_not_at_top(tmp_path):
    # Marker text appears in file, but after some leading content — must fail.
    content = (
        "<?php\n"
        "// some other comment\n"
        "// AUTO-GENERATED by frontend-builder.\n"
        "// Edits will be overwritten. Modify DESIGN.md §5 or block-spec.yaml instead.\n"
        "<section></section>"
    )
    project = _make_project(tmp_path, {"hero": content})
    r = subprocess.run([sys.executable, str(SCRIPT), str(project)], capture_output=True, text=True)
    assert r.returncode != 0


def test_fails_when_a_block_missing_marker(tmp_path):
    project = _make_project(tmp_path, {
        "hero": MARKER + "<section></section>",
        "faq": "<?php // not generated by frontend-builder\n",
    })
    r = subprocess.run([sys.executable, str(SCRIPT), str(project)], capture_output=True, text=True)
    assert r.returncode != 0
    assert "faq" in r.stderr or "faq" in r.stdout


def test_passes_when_no_blocks_dir(tmp_path):
    project = tmp_path / "proj"
    (project / "08_КОД" / "wp-theme").mkdir(parents=True)
    r = subprocess.run([sys.executable, str(SCRIPT), str(project)], capture_output=True, text=True)
    assert r.returncode == 0, r.stderr
