#!/usr/bin/env python3
"""Emit inc/lp-preview-panel-axes.php registering the lp_preview_panel_axes filter."""
import argparse
import os
import sys
import yaml

HERO_LABELS = {
    "static": "Static",
    "parallax": "Parallax",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    ap.add_argument("--default-palette", required=True)
    ap.add_argument("--hero", required=True, help="comma-separated hero ids")
    ap.add_argument("--default-hero", required=True)
    args = ap.parse_args()

    src = os.path.join(args.project, "04_БРЕНД", "palettes.yaml")
    with open(src, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    palettes = data.get("palettes", []) or []
    palette_by_id = {p["id"]: p for p in palettes}

    if args.default_palette not in palette_by_id:
        print(f"ERROR: --default-palette {args.default_palette!r} not in project snapshot", file=sys.stderr)
        sys.exit(1)

    hero_ids = [h.strip() for h in args.hero.split(",") if h.strip()]
    unknown = [h for h in hero_ids if h not in HERO_LABELS]
    if unknown:
        print(f"ERROR: unknown hero id(s): {unknown}", file=sys.stderr)
        sys.exit(1)
    if args.default_hero not in hero_ids:
        print(f"ERROR: --default-hero {args.default_hero!r} not in --hero list", file=sys.stderr)
        sys.exit(1)

    palette_max_key_len = max(len(pid) for pid in palette_by_id) if palette_by_id else 0
    hero_max_key_len = max(len(h) for h in hero_ids) if hero_ids else 0

    def fmt_option(key, label, max_len):
        pad = " " * (max_len - len(key))
        return f"            '{key}'{pad} => '{label}',"

    lines = [
        "<?php",
        "/**",
        " * Generated by scripts/generate-axes-filter.py. Do not edit.",
        " * Registers the lp_preview_panel_axes filter for this theme.",
        " */",
        "",
        "add_filter( 'lp_preview_panel_axes', function ( $axes ) {",
        "    $axes['palette'] = [",
        "        'label'             => 'Палитра',",
        f"        'default'           => '{args.default_palette}',",
        "        'body_class_prefix' => 'theme-',",
        "        'options' => [",
    ]
    for pid in palette_by_id:
        lines.append(fmt_option(pid, palette_by_id[pid]["name"], palette_max_key_len))
    lines += [
        "        ],",
        "    ];",
        "    $axes['hero'] = [",
        "        'label'             => 'Hero',",
        f"        'default'           => '{args.default_hero}',",
        "        'body_class_prefix' => 'hero--',",
        "        'options' => [",
    ]
    for h in hero_ids:
        lines.append(fmt_option(h, HERO_LABELS[h], hero_max_key_len))
    lines += [
        "        ],",
        "    ];",
        "    return $axes;",
        "} );",
        "",
    ]

    dest = os.path.join(args.project, "08_КОД", "wp-theme", "inc", "lp-preview-panel-axes.php")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines))
    print(f"wrote {dest}")


if __name__ == "__main__":
    main()
