#!/usr/bin/env python3
"""Generate body.theme-<id> CSS blocks from <project>/04_БРЕНД/palettes.yaml."""
import argparse
import os
import sys
import yaml

# Ordered to match neuroupgrade-v2 main.css style for diff readability.
TOKEN_ORDER = [
    "bg_base", "bg_section", "bg_elevated",
    "border_subtle", "border_strong",
    "text_primary", "text_soft", "text_dim",
    "accent_mint", "accent_teal", "accent_coral",
    "accent_coral_hover", "accent_coral_text",
    "accent_rgb_mint", "accent_rgb_coral",
    "card_bg", "card_border", "card_border_hover",
    "accent_cta_glow_opacity",
]


def yaml_key_to_css(key):
    return "--" + key.replace("_", "-")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--project", required=True)
    args = ap.parse_args()

    src = os.path.join(args.project, "04_БРЕНД", "palettes.yaml")
    with open(src, "r", encoding="utf-8") as f:
        data = yaml.safe_load(f) or {}
    palettes = data.get("palettes", []) or []

    out_lines = ["/* Generated by scripts/generate-palette-css.py. Do not edit. */", ""]
    for p in palettes:
        out_lines.append(f"body.theme-{p['id']} {{")
        tokens = p.get("tokens", {})
        for key in TOKEN_ORDER:
            if key not in tokens:
                print(f"ERROR: palette {p['id']} missing token {key}", file=sys.stderr)
                sys.exit(1)
            out_lines.append(f"  {yaml_key_to_css(key)}: {tokens[key]};")
        out_lines.append("}")
        out_lines.append("")

    dest_dir = os.path.join(args.project, "08_КОД", "wp-theme", "assets", "css")
    os.makedirs(dest_dir, exist_ok=True)
    dest = os.path.join(dest_dir, "palettes.css")
    with open(dest, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(out_lines))

    print(f"wrote {dest} ({len(palettes)} palette(s))")


if __name__ == "__main__":
    main()
