category: header
created: '2026-06-01'
display_name_ru: header-003 (minimal)
has_bg_image: false
id: header-003
layout_pattern: minimal
signature: header|minimal|[content]|bg:false
slots:
- name: header-aria-label
  type: text
- name: brand-aria-label
  type: text
- name: brand-link
  type: text
- name: logo-image-alt
  type: text
- name: logo-image
  type: text
- name: brand-name
  type: text
- name: navigation-aria-label
  type: text
- name: nav-link-1-url
  type: text
- name: nav-link-1-label
  type: text
- name: nav-link-2-url
  type: text
- name: nav-link-2-label
  type: text
- name: nav-link-3-url
  type: text
- name: nav-link-3-label
  type: text
- name: nav-link-4-url
  type: text
- name: nav-link-4-label
  type: text
- name: contact-link
  type: text
- name: contact-label
  type: text
- name: contact-value
  type: text
- name: cta-link
  type: text
- name: cta-label
  type: text
source: cleaned
type: header
variant: null
